sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

script: 
  - ./build_all.sh
  - ./bin/tests

before_install:
  - chmod 755 build_all.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - sudo apt-get install libgtest-dev
  - sudo apt-get install google-mock
  - sudo apt-get update
  - chmod 755 ci/build_gtest.sh
  - sudo ci/build_gtest.sh
  - pip install --user cpp-coveralls

after_success:
  - cpp-coveralls --exclude externals --include src --include tests --gcov-options '\-lp' --verbose
